name: Run GPT-J

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run_gptj:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Step 2: Install dependencies (Torch and Transformers libraries)
      - name: Install dependencies
        run: |
          pip install --upgrade pip || echo "Failed to upgrade pip"
          pip install torch transformers || echo "Failed to install torch and transformers"

      # Optional: Wait for a few seconds to ensure everything is set up
      - name: Wait for setup
        run: sleep 5

      # Step 3: Run GPT-J
      - name: Run GPT-J
        run: |
          python -c "from transformers import AutoModelForCausalLM, AutoTokenizer; \
          model = AutoModelForCausalLM.from_pretrained('EleutherAI/gpt-j-6B'); \
          tokenizer = AutoTokenizer.from_pretrained('EleutherAI/gpt-j-6B'); \
          inputs = tokenizer('Hello, how can I assist you?', return_tensors='pt'); \
          outputs = model.generate(**inputs); \
          print(tokenizer.decode(outputs[0]))" || echo "Failed to run GPT-J"
